apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: securesecret
  labels:
    app.kubernetes.io/instance: securesecret
spec:
  replicas: 1
  serviceName: secur-hls
  selector:
    matchLabels:
      app: alp-dep
  template:
    metadata:
      labels:
        app: alp-dep
      annotations:
    spec:
      containers:
      - name: secure-reader
        image:  alpine
        imagePullPolicy: Always
        command: ["/bin/sh","-c"]
        args: ["echo 'Read secrets';  rm -rf /etc/share-vol/sec-vol; sleep 1000"]
        volumeMounts:
        - mountPath: "/etc/share-vol"
          name: securesecret-ss-secuser-claim
      initContainers:
      - name: base-secret-injector
        image: alpine
        args:
        - cp
        - "-rf"
        - /etc/sec-vol/
        - /etc/share-vol/
        volumeMounts:
        - mountPath: "/etc/share-vol"
          name: securesecret-ss-secuser-claim
        - mountPath: "/etc/sec-vol"
          name : sec-volume
      volumes:
      - name: sec-volume
        secret:
          secretName: securesecr-user-secret

  volumeClaimTemplates:
  - metadata:
      name: securesecret-ss-secuser-claim
    spec:
      accessModes:
        - ReadWriteOnce
      storageClassName: default
      resources:
        requests:
          storage: "10Mi"
